jwt:
  signerKey: "FtnneCAPzaRwuVV6JBy1OgtRhoq08Fp/JYu5OFdCj+zPqDyn8+1VlXtwBcX8u4CJ"
  valid-duration: 86400
  refreshable-duration: 604800

server:
  port: 8080
  servlet:
    context-path: /resident-management

spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/resident_management}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  data:
    redis:
      host: localhost
      port: 6379

file:
  uploadDir: uploads/
  baseUrl: "http://localhost:8080"

payos:
  client-id: "1774adbb-a63b-42a1-8da3-ef74701f9174"
  api-key: "1738f8f1-cc14-4469-9cad-6c8a242bf7f5"
  checksum-key: "2e43dbb18dbb734dda13c5adb1614af5426e8ff164c3bb0452836623b08b642d"