jwt:
  signerKey: "FtnneCAPzaRwuVV6JBy1OgtRhoq08Fp/JYu5OFdCj+zPqDyn8+1VlXtwBcX8u4CJ"
  valid-duration: 3600
  refreshable-duration: 7200

server:
  port: 8080
  servlet:
    context-path: /resident-management

spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/resident_management}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  data:
    redis:
      host: localhost
      port: 6379

file:
  uploadDir: uploads/
  baseUrl: "http://localhost:8080"